# To see the complete list of configurable parameters see:
# https://github.com/ray-project/ray/blob/master/rllib/agents/trainer.py


# === Settings for Rollout Worker processes ===
num_workers: 1
# rollout_fragment_length: 16
# num_envs_per_worker: 
# batch_mode: "truncate_episodes"


# === Settings for the Trainer process ===
num_gpus: 0.6
train_batch_size: 128
# optimizer: "Adam"
model: {

  # == Atari ==
  dim: 300,

  # === Built-in options ===
  conv_filters: [
    [16, [5, 5], 4],
    [32, [5, 5], 2],
    [32, [5, 5], 2],
    [64, [5, 5], 1],
    [64, [5, 5], 2],
    [128, [5, 5], 2],
    [512, [5, 5], 1],
  ]

  # == LSTM ==
  # "use_lstm": False,
  # "max_seq_len": 20,
  # "lstm_cell_size": 256,
  # "lstm_use_prev_action": False,
  # "lstm_use_prev_reward": False,
}


# === PPO ===
# use_critic: True
# use_gae: True
# lambda: 1.0
# kl_coeff: 0.2
# sgd_minibatch_size: 128
# shuffle_sequences: True
# num_sgd_iter: 30
# lr_schedule: None
# entropy_coeff: 0.0
# entropy_coeff_schedule: None
# clip_param: 0.3
# vf_clip_param: 10.0
# grad_clip: None
# kl_target: 0.01


# === Debug Settings ===
# monitor: False
# log_level: "WARN"
# log_sys_usage: True


# === Deep Learning Framework Settings ===
framework: "torch"


# === Exploration Settings ===
# exploration_config: {
#     "type": "EpsilonGreedy",
#     "initial_epsilon": 1.0,
#     "final_epsilon": 0.02,
#     "epsilon_timesteps": 2000000
#   }
# exploration_config: {
#   type: "SoftQ",
#   temperature: 1.0,
# }


# === Evaluation Settings ===
# evaluation_interval: None
# evaluation_num_episodes: 10
# in_evaluation: False
# evaluation_config: {}
# evaluation_num_workers: 0
# custom_eval_function: None


# === Advanced Rollout Settings ===
# remote_worker_envs: False
# seed: None
# extra_python_environs_for_driver: {}
# extra_python_environs_for_worker: {}
# timesteps_per_iteration: 20000


# === Advanced Resource Settings ===
num_cpus_per_worker: 11
# num_gpus_per_worker: 1
# num_cpus_for_driver: 1
# memory: 0
# object_store_memory: 0
# memory_per_worker: 0
# object_store_memory_per_worker: 0


# === Environment Settings ===
# gamma: 0.99
# horizon: None
# soft_horizon: False
# no_done_at_end: False
# normalize_actions: False
# clip_rewards: None
# clip_actions: True
# lr: 0.0025
env_config:
  carla:
    host: "localhost"
    timeout: 30.0
    timestep: 0.05
    retries_on_error: 25
    resolution_x: 600
    resolution_y: 600
    quality_level: "Low"
    enable_map_assets: True
    enable_rendering: True
    show_display: True

  experiment:
    hero:
      blueprint: "vehicle.audi.a2"
      sensors:
        cam_sem_seg_front:
          type: "sensor.camera.semantic_segmentation"
          transform: "0,0,2,0,0,0"
          image_size_x: 300
          image_size_y: 300
        cam_sem_seg_left:
          type: "sensor.camera.semantic_segmentation"
          transform: "0,0,2,0,-90.0,0"
          image_size_x: 300
          image_size_y: 300
        cam_sem_seg_right:
          type: "sensor.camera.semantic_segmentation"
          transform: "0,0,2,0,90.0,0"
          image_size_x: 300
          image_size_y: 300
        # lidar:
        #   type: "sensor.lidar.ray_cast "
        #   transform: "0,0,2,0,0,0"
      spawn_points: [
        "-130.80254883,103.26209961,1",
        "-258.58019531,0.32128639,1",
        "-130.50441406,136.6653125,1",
        "-258.58871094,-3.82127594,1",
        "-188.099101566,-101.55841797,1",
        "-120.81304688,-127.37759766,1",
        "143.90660156,1.53764084,1",
        "-51.00605469,112.90189453,1",
        "-127.00455078,136.63408203,1",
        "-248.39375,86.93456055,1",
        "82.57344727,-143.86496094,1",
        "60.38806641,-87.59395508,1",
        "76.17259766,145.39817383,1",
        "-169.49910156, -144.75841797,1",
        "106.59984375, -48.29285156, 1",
        "59.72867188, 95.25668945, 1",
        "-276.03814453, 58.77165039, 1",
        "-239.69027344, -95.16041016, 1",
        "-191.54279297, 117.29594727, 1",
        "103.57628906, -62.79506836, 1",
        "151.52549805, 80.119375, 1",
        "70.33907227, 93.09503906, 1",
        "-195.05011719, 76.0861377, 1",
        "36.48416992, -76.58737793, 1",
        "-54.1016748, 13.33402832, 1",
        "-184.58589844, -53.54149902, 1",
        "90.15171875, 1.95712494, 1",
        "37.87285156, -128.50666016, 1",
        "-88.96650391, 94.96491211, 1",
        "-18.79371826, -84.42214844, 1",
        "-124.77713867, -59.83091309, 1",
        "-162.53725586, -84.63864258, 1",
        "69.41578613, -190.24716797, 1",
        "207.23964844, -11.23129517, 1",
        "37.30215332, 208.75220703, 1"
        ]
    background_activity:
      n_vehicles: 0
      n_walkers: 0
      tm_hybrid_mode: True
    town: "Town05_Opt"
    others:
      framestack: 4
      max_time_idle: 600
      max_time_episode: 6400